server:
  port: 8081
springdoc:
  swagger-ui:
    url: /open-api-docs.yaml
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${TRIGON_JDBC_URL}
    username: ${TRIGON_DB_USERNAME}
    password: ${TRIGON_DB_PASS}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    driverClassName: org.postgresql.Driver

  data:
    elasticsearch:
      cluster-nodes: ${ELASTIC_SEARCH_URL}
      cluster-name: ${ELASTIC_SEARCH_CLUSTER_NAME}
      cluster-username: ${ELASTIC_SEARCH_USERNAME}
      cluster-password: ${ELASTIC_SEARCH_PASSWORD}
      repositories:
        enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TRIGON_OKTA_ISSUER}

  cloud:
    gcp:
      bigquery:
        project-id: ${GCP_PROJECT_ID}
        datasetName: ${GCP_BQ_REC_DATASET_NAME}

com:
  bmg:
    sap:
      md:
        url: ${SAP_MD_ENDPOINT_URL}
        scheduling:
          sap-md-trigger-time: ${SAP_MD_TRIGGER_TIME} # 0 0 0 * * * (every day at midnight) second, minute, hour, day of month, month, day(s) of week
          maximum-days-to-wait: ${SAP_MD_MAXIMUM_DAYS_TO_WAIT} # maximum days to wait to sync the Master Data
          md-sync-enable: ${SAP_MD_SYNC_ENABLE} # true -> MD should Sync and false -> MD Should not sync
        basic-auth:
          username: ${SAP_MD_USERNAME}
          password: ${SAP_MD_PASSWORD}
      direct-fi:
        url: ${SAP_DIRECT_FI_ENDPOINT_URL}
        basic-auth:
          username: ${SAP_DIRECT_FI_USERNAME}
          password: ${SAP_DIRECT_FI_PASSWORD}

sftp:
  sap-md-host: ${SAP_MD_HOST}
  sap-md-port: ${SAP_MD_PORT}
  sap-md-user: ${SAP_MD_USER}
  sap-md-pwd: ${SAP_MD_PWD}
  sap-md-unprocessed-dir: ${SAP_MD_UNPROCESSED_DIR}
  sap-md-processed-dir: ${SAP_MD_PROCESSED_DIR}
  sap-md-error-dir: ${SAP_MD_ERROR_DIR}
  sap-md-direct-fi-dir: ${SAP_MD_DIRECT_FI_DIR}
  sap-md-watch-interval-in-min: ${SAP_MD_WATCH_INTERVAL_IN_MIN}


sap-td:
  cron-jobs-enabled: ${SAP_TD_CRON_JOBS_ENABLED}
  url: ${SAP_TRANSACTIONAL_ENDPOINT_URL}
  username: ${SAP_TRANSACTIONAL_USERNAME}
  password: ${SAP_TRANSACTIONAL_PASSWORD}
  scheduler-interval-in-min: ${SAP_TD_SCHEDULER_INTERVAL_IN_MIN}

sendgrid:
  api:
    key: ${SEND_GRID_API_KEY}
  from-email: ${SEND_GRID_FROM_MAIL}
  sap-md-error:
    template-id: ${SAP_MD_ERROR_TEMPLATE_ID}
    to_emails: ${SAP_MD_ERROR_TO_EMAILS}
    cc_emails: ${SAP_MD_ERROR_CC_EMAILS}

cloud:
  gcs:
    project-id: ${GCP_TRIGON_PROJECT_ID}
    bucket-name: ${GCP_DIRECT_FI_BUCKET_NAME}