package com.bmg.deliver.model.product;

import lombok.Data;

import java.util.ArrayList;
import java.util.List;

@Data
public class CaptureComponent {
	private long productId;
	private Site site;
	private String royaltyCompliance;
	private String entityStatus;
	private String lockedStatus;
	private boolean contractSupplyChainApproved;
	private boolean isMetadataConfirmed;
	private boolean isCancelled;
	private boolean isCatalogueIngestion;
	private boolean wasLiveWhenAcquired;
	private String barcode;
	private String productCode;
	private String grId;
	private List<String> altProductCodes = new ArrayList<>();
	private Boolean isDeliveredAsUPC;
	private String releaseDate;
	private String originalReleaseDate;
	private String artistName;
	private String title;
	private String versionTitle;
	private String internalVersionTitle;
	private String productTitle;
	private Genre genre;
	private String audioQuality;
	private long duration;
	private boolean isRemaster;
	private String ownershipType;
	private long copyrightYear;
	private String copyrightOwner;
	private String copyrightNotice;
	private long artworkYear;
	private String artworkOwner;
	private String artworkNotice;
	private String parentalAdvisoryArtworkIndicator;
	private String parentalAdvisoryLyricsIndicator;
	private RepertoireOwnerCompany repertoireOwnerCompany;
	private Label label;
	private CaptureProduct.SAPInternalCode sapInternalCode;
	private CaptureProduct.CaptureProductFormat format;
	private CaptureProduct.RightsCode contractualRightsCode;
	private CaptureProduct.RightsCode marketingRightsCode;
	private Language metadataLanguage;
	private boolean isSoundTrack;
	private boolean isDjmix;
	private boolean isKaraoke;
	private boolean isLive;
	private boolean isRemix;
	private boolean isPartial;
	private long numberOfTracks;
	private long numberOfTracksByBMG;
	private long numberOfComponents;
	private boolean isCompilation;
	private boolean isComponent;
	private boolean isPackageOnly;
	private boolean isLicenced;
	private boolean isMultipleArtists;
	private boolean hasBooklet;
	private boolean isPromo;
	private boolean menaCompliance;
	private String coordinator;
	private String manager;
	private String created;
	private String updated;
	private String notes;
	private List<String> translationCompliances = new ArrayList<>();
	private List<CaptureProduct.Project> projects = new ArrayList<>();
	private String includesDownloadCard;
	private List<CaptureTrack> tracks;
	private List<CaptureProduct.ProductContributor> productContributors;
}
