#!/bin/sh

test "" != "$(egrep '^(build|ci|docs|feature|fix|performance|refactor|revert|style|test){1}(\([A-Z]{2,}-[0-9]{1,}[[:punct:]])(!)?: ([[:alnum:]])+([[:space:][:print:]]*)' $1)" || {
    echo ""
    echo "Error: Commit message must follow conventional commits with JIRA ticket as scope in parentheses."
    echo "The syntax for a commit message is:"
    echo ""
    echo "    <type>(<ticket>): <description>"
    echo ""
    echo "Allowed types are:"
    echo ""
    echo "    build|ci|docs|feature|fix|performance|refactor|revert|style|test"
    echo ""
    echo "For example, 'feature(AAD-123): test' is a valid commit message."
    echo "For more details, please read about conventional commits: https://www.conventionalcommits.org/en/v1.0.0/"
    exit 1

}